export const CONFIG_VAR = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',

  // DATABASE
  DATABASE_URL: 'DATABASE_URL',

  // JWT SECRET

  // JWT SECRET TOKEN TYPE
  FORGOT_JWT_SECRET: 'FORGOT_JWT_SECRET',

  // JWT SECRET TOKEN TYPE
  EMAIL_JWT_SECRET: 'EMAIL_JWT_SECRET',

  // JWT EXPIRES IN

  JWT_FORGOT_EXPIRES_IN: 'JWT_FORGOT_EXPIRES_IN',
  JWT_EMAIL_EXPIRES_IN: 'JWT_EMAIL_EXPIRES_IN',

  // REDIS
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  REDIS_DB_QUEUE: 'REDIS_DB_QUEUE',
  REDIS_DB_CACHE: 'REDIS_DB_CACHE',

  // AWS
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION: 'AWS_REGION',
  AWS_ENDPOINT: 'AWS_ENDPOINT',
  AWS_BUCKET_S3: 'AWS_BUCKET_S3',

  // FB
  APP_FACEBOOK_ID: 'APP_FACEBOOK_ID',
  APP_FACEBOOK_SECRET: 'APP_FACEBOOK_SECRET',

  //GG
  APP_GOOGLE_ID: 'APP_GOOGLE_ID',
  APP_GOOGLE_SECRET: 'APP_GOOGLE_SECRET',

  // MAIL GUN,
  MAIL_USER: 'MAIL_USER',
  MAIL_PASSWORD: 'MAIL_PASSWORD',

  // CLERK
  CLERK_PUBLIC_KEY: 'CLERK_PUBLIC_KEY',
  CLERK_SECRET_KEY: 'CLERK_SECRET_KEY',
  CLERK_JWT_KEY: 'CLERK_JWT_KEY',
  CLERK_API_URL: 'CLERK_API_URL',

  // STRIPE
  STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
  STRIPE_PUBLISH_KEY: 'STRIPE_PUBLISH_KEY',
  STRIPE_WEB_HOOK_SECRET: 'STRIPE_WEB_HOOK_SECRET',
  STRIPE_WEB_HOOK_SECRET_CONNECTED: 'STRIPE_WEB_HOOK_SECRET_CONNECTED',
};

export const DEFAULT_PORT = '3000';
