export const CONFIG_VAR = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',

  // DATABASE
  DATABASE_URL: 'DATABASE_URL',

  // JWT SECRET
  NURSE_JWT_SECRET: 'NURSE_JWT_SECRET',
  NURSE_JWT_REFRESH_SECRET: 'NURSE_JWT_REFRESH_SECRET',
  DOCTOR_JWT_SECRET: 'DOCTOR_JWT_SECRET',
  DOCTOR_JWT_REFRESH_SECRET: 'DOCTOR_JWT_REFRESH_SECRET',
  OWNER_JWT_SECRET: 'OWNER_JWT_SECRET',
  OWNER_JWT_REFRESH_SECRET: 'OWNER_JWT_REFRESH_SECRET',
  ADMIN_JWT_SECRET: 'ADMIN_JWT_SECRET',
  ADMIN_JWT_REFRESH_SECRET: 'ADMIN_JWT_REFRESH_SECRET',

  // JWT SECRET TOKEN TYPE
  INVITATION_JWT_SECRET: 'INVITATION_JWT_SECRET',
  FORGOT_JWT_SECRET: 'FORGOT_JWT_SECRET',

  // JWT EXPIRES IN
  JWT_ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  JWT_INVITATION_EXPIRES_IN: 'JWT_INVITATION_EXPIRES_IN',
  JWT_FORGOT_EXPIRES_IN: 'JWT_FORGOT_EXPIRES_IN',

  // REDIS
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  REDIS_DB_QUEUE: 'REDIS_DB_QUEUE',
  REDIS_DB_CACHE: 'REDIS_DB_CACHE',

  // FE
  FE_CHOOSE_PASSWORD_URL: 'FE_CHOOSE_PASSWORD_URL',
  FE_CREATE_PROFILE_URL: 'FE_CREATE_PROFILE_URL',

  FE_ADMIN_RESET_PASSWORD_URL: 'FE_ADMIN_RESET_PASSWORD_URL',
  FE_OWNER_RESET_PASSWORD_URL: 'FE_OWNER_RESET_PASSWORD_URL',
  FE_NURSE_RESET_PASSWORD_URL: 'FE_NURSE_RESET_PASSWORD_URL',
  FE_DOCTOR_RESET_PASSWORD_URL: 'FE_DOCTOR_RESET_PASSWORD_URL',

  FE_NURSE_CHOOSE_PASSWORD_URL: 'FE_NURSE_CHOOSE_PASSWORD_URL',
  FE_NURSE_CREATE_PROFILE_URL: 'FE_NURSE_CREATE_PROFILE_URL',

  FE_DOCTOR_CHOOSE_PASSWORD_URL: 'FE_DOCTOR_CHOOSE_PASSWORD_URL',
  FE_DOCTOR_CREATE_PROFILE_URL: 'FE_DOCTOR_CREATE_PROFILE_URL',
  // MAIL
  MAIL_USER: 'MAIL_USER',
  MAIL_PASSWORD: 'MAIL_PASSWORD',

  // AWS
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION: 'AWS_REGION',
  AWS_ENDPOINT: 'AWS_ENDPOINT',
  AWS_BUCKET_S3: 'AWS_BUCKET_S3',

  // FB
  APP_FACEBOOK_ID: 'APP_FACEBOOK_ID',
  APP_FACEBOOK_SECRET: 'APP_FACEBOOK_SECRET',

  //GG
  APP_GOOGLE_ID: 'APP_GOOGLE_ID',
  APP_GOOGLE_SECRET: 'APP_GOOGLE_SECRET',
};

export const DEFAULT_PORT = 3000;
