/** To avoid using magic strings */

const NODE_ENV = 'NODE_ENV';
const PORT = 'PORT';

// JWT
const JWT_SECRET = 'JWT_SECRET';
const JWT_EXPIRES_IN = 'JWT_EXPIRES_IN';
const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
const JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN';

// REDIS
const REDIS_HOST = 'REDIS_HOST';
const REDIS_PORT = 'REDIS_PORT';
const REDIS_PASSWORD = 'REDIS_PASSWORD';

// MONGODB
const MONGODB_URI = 'MONGODB_URI';

// ADMIN ACCOUNT
const DEFAULT_ADMIN_USERNAME = 'DEFAULT_ADMIN_USERNAME';
const DEFAULT_ADMIN_PASSWORD = 'DEFAULT_ADMIN_PASSWORD';
const DEFAULT_ADMIN_EMAIL = 'DEFAULT_ADMIN_EMAIL';

// SENDGRID
const SENDGRID_API_KEY = 'SENDGRID_API_KEY';

// STRIPE
const STRIPE_PUBLIC_KEY = 'STRIPE_PUBLIC_KEY';
const STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY';

// CLOUDINARY
const CLOUDINARY_NAME = 'CLOUDINARY_NAME';
const CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY';
const CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET';

// FIREBASE
const FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID';
const FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY';
const FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL';

export {
  NODE_ENV,
  PORT,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  MONGODB_URI,
  DEFAULT_ADMIN_USERNAME,
  DEFAULT_ADMIN_PASSWORD,
  DEFAULT_ADMIN_EMAIL,
  SENDGRID_API_KEY,
  STRIPE_PUBLIC_KEY,
  STRIPE_SECRET_KEY,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
};
